mysqldata:
  image: harshjv/mysql-data:0.9.16-1.0

composerdata:
  image: harshjv/composer-data:0.9.16-1.0

mysql:
  image: tutum/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_PASS: password
  volumes_from:
    - mysqldata
  volumes:
    - ./mysql:/var/lib/mysql

phpmyadmin:
  image: sauveterre/docker-phpmyadmin
  environment:
    PMA_SECRET: yW5gmMTijQt7GcGIgk6frcjN

phpnginx:
  image: sauveterre/docker-php-nginx
  volumes_from:
    - composerdata
  links:
    - mysql:mysql
  ports:
    - "80:80" # Nginx
  volumes_from:
    - phpmyadmin
  volumes:
    - ./nginx:/etc/nginx/sites-enabled
    - ./composer/:/root/.composer
    - /home/elie/Workspace/Doctr/backend/:/var/www/backend
    - /home/elie/Workspace/Doctr/wordpress/:/var/www/wordpress

gulp:
  image: harshjv/bower-gulp:1.0
