mysqldata:
  image: harshjv/mysql-data:0.9.16-1.0

composerdata:
  image: harshjv/composer-data:0.9.16-1.0

mysql:
  image: tutum/mysql
  environment:
    MYSQL_PASS: password
  volumes_from:
    - mysqldata
  volumes:
    - ./mysql:/var/lib/mysql

phpmyadmin:
  image: sauveterre/docker-phpmyadmin
  environment:
    PMA_SECRET: yW5gmMTijQt7GcGIgk6frcjN

nodejs:
  image: sauveterre/docker-nodejs
  volumes:
    - /home/elie/Workspace/Doctr/:/var/www

redis:
  image: redis:3.0.5
  volumes:
    - ./redis:/data
  ports:
    - "6379"

phpnginx:
  image: sauveterre/docker-php-nginx
  volumes_from:
    - composerdata
  links:
    - mysql:mysql
    - redis
  ports:
    - "80:80" # Nginx
#    - "8000:8000" # Laravel serve
#    - "3000:3000" # Redis
  volumes_from:
    - phpmyadmin
  volumes:
    - ./nginx:/etc/nginx/sites-enabled
#    - ./logs:/var/log/nginx
    - ./composer/:/root/.composer
    - /home/elie/Workspace/Doctr/backend/:/var/www/backend
    - /home/elie/Workspace/Doctr/wordpress/:/var/www/wordpress
