#mysqldata:
#  image: harshjv/mysql-data:0.9.16-1.0

composerdata:
  image: harshjv/composer-data:0.9.16-1.0

#mysql:
#  image: harshjv/mysql:0.9.16-1.0
#  environment:
#    MYSQL_PASS: root
#  volumes_from:
#    - mysqldata

#mysql:
#  image: mariadb
#  environment:
#    MYSQL_ROOT_PASSWORD: ''

mysql:
  image: tutum/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_PASS: password

phpnginx:
  image: sauveterre/php-nginx
  volumes_from:
    - composerdata
  links:
    - mysql:mysql
  ports:
    - "80:80" # Nginx
  volumes:
    - ./nginx:/etc/nginx/sites-enabled
    - /home/elie/Workspace/Doctr/backend/:/var/www
    - ./logs:/var/log/nginx

gulp:
  image: harshjv/bower-gulp:1.0
